import { useState, useEffect } from 'react';
import { useNavigate, useLocation } from 'react-router-dom';
import { useForm } from 'react-hook-form';
import { yupResolver } from '@hookform/resolvers/yup';
import * as yup from 'yup';
import { toast } from 'react-toastify';
import { useAuth } from '../../context/AuthContext';

const loginValidationSchema = yup.object().shape({
  email: yup.string().email('Please enter a valid corporate email configuration style').required('Corporate email authentication token identifier is required'),
  password: yup.string().min(6, 'Security credentials access key must be at least 6 characters').required('Access credentials key is required'),
  rememberMe: yup.boolean().default(false),
});

export const useLogin = () => {
  const navigate = useNavigate();
  const location = useLocation();
  const { login, isAuthenticated } = useAuth();

  // Core Status Banner Tracking Matrices
  const [apiError, setApiError] = useState<string | null>(null);
  const [infoMessage, setInfoMessage] = useState<string | null>(null);
  const [isSubmitting, setIsSubmitting] = useState<boolean>(false);
  const [showPassword, setShowPassword] = useState<boolean>(false);

  // Target routing parameter parsed fallback
  const from = (location.state as any)?.from?.pathname || '/dashboard';

  // Guard routing loop if session context token already verified
  useEffect(() => {
    if (isAuthenticated) {
      navigate('/dashboard', { replace: true });
    }

    // Capture explicit URL string flag parameters generated by interceptor drops
    const searchParams = new URLSearchParams(location.search);
    if (searchParams.get('expired') === 'true') {
      setInfoMessage('Your active corporate security token session has expired. Please authenticate.');
    }
  }, [isAuthenticated, navigate, location.search]);

  const { register, handleSubmit, formState: { errors } } = useForm({
    resolver: yupResolver(loginValidationSchema),
    defaultValues: {
      email: '',
      password: '',
      rememberMe: false
    }
  });

  const togglePasswordVisibility = () => {
    setShowPassword((prev) => !prev);
  };

  const onSubmitLogin = async (data: any) => {
    setIsSubmitting(true);
    setApiError(null);
    try {
       await login({ email: data.email, password: data.password });
        toast.success('Welcome to Quantra.');
        navigate(from, { replace: true });
     
    } catch (err: any) {
      const errMsg = err.response?.data?.message || 'Inbound networking infrastructure dropped validation package frames.';
      setApiError(errMsg);
      toast.error(errMsg);
    } finally {
      setIsSubmitting(false);
    }
  };

  return {
    register,
    handleSubmit,
    errors,
    apiError,
    infoMessage,
    isSubmitting,
    showPassword,
    togglePasswordVisibility,
    onSubmitLogin,
  };
};