INSERT INTO color (color_id,color_name, color_description) VALUES
(gen_random_uuid(),'Black', '#000000'),
(gen_random_uuid(),'White', '#FFFFFF'),
(gen_random_uuid(),'Red', '#FF0000'),
(gen_random_uuid(),'Lime', '#00FF00'),
(gen_random_uuid(),'Blue', '#0000FF'),
(gen_random_uuid(),'Yellow', '#FFFF00'),
(gen_random_uuid(),'Cyan', '#00FFFF'),
(gen_random_uuid(),'Magenta', '#FF00FF'),
(gen_random_uuid(),'Silver', '#C0C0C0'),
(gen_random_uuid(),'Gray', '#808080'),
(gen_random_uuid(),'Maroon', '#800000'),
(gen_random_uuid(),'Olive', '#808000'),
(gen_random_uuid(),'Green', '#008000'),
(gen_random_uuid(),'Purple', '#800080'),
(gen_random_uuid(),'Teal', '#008080'),
(gen_random_uuid(),'Navy', '#000080'),
(gen_random_uuid(),'Orange', '#FFA500'),
(gen_random_uuid(),'Brown', '#A52A2A'),
(gen_random_uuid(),'Gold', '#FFD700'),
(gen_random_uuid(),'Pink', '#FFC0CB'),
(gen_random_uuid(),'Coral', '#FF7F50'),
(gen_random_uuid(),'Turquoise', '#40E0D0'),
(gen_random_uuid(),'Lavender', '#E6E6FA'),
(gen_random_uuid(),'Salmon', '#FA8072');

INSERT INTO size (size_id, size_name, size_description) VALUES
(gen_random_uuid(), 'XXS','Extra Extra Small'),
(gen_random_uuid(), 'XS','Extra Small'),
(gen_random_uuid(), 'S','Small'),
(gen_random_uuid(), 'M','Medium'),
(gen_random_uuid(), 'L', 'Large'),
(gen_random_uuid(), 'XL', 'Extra Large'),
(gen_random_uuid(), 'XXL','Extra Extra Large');